# Generated by Django 5.2.6 on 2025-09-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='incluido',
            field=models.JSONField(default=list),
        ),
    ]
