# Generated by Django 5.2.6 on 2025-09-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_destino_calificacion_destino_incluido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='destinos',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='categoria',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='catalogo.paquete'),
        ),
        migrations.AddField(
            model_name='itinerario',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='catalogo.servicio'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicios',
            field=models.ManyToManyField(to='catalogo.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_servicio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dias',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagenes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='servicio',
            name='incluido',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='itinerario',
            field=models.ManyToManyField(related_name='paquetes', to='catalogo.itinerario'),
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
    ]
