# Generated by Django 5.2.6 on 2025-09-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_paquete_destinos_remove_paquete_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='catalogo.categoria'),
        ),
    ]
