# Generated by Django 5.2.6 on 2025-09-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_paquete_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerario',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='servicio',
        ),
    ]
