# Generated by Django 5.2.6 on 2025-09-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaacompanante',
            name='acompanante',
            field=models.ForeignKey(db_column='visitante_id', on_delete=django.db.models.deletion.RESTRICT, related_name='reservas_acompanantes', to='reservas.acompanante'),
        ),
        migrations.AlterModelTable(
            name='reservaacompanante',
            table='reservas_reservavisitante',
        ),
    ]
